### ISSUE TITLE
Backlink to original repo

### ISSUE THREAD

**Issue by bumbummen99** [treeStoneIT/shopping-cart#3]
Hey,

thank you for the great package, it would be nice if you could also include a backlink to the [original repo](https://github.com/Crinsane/LaravelShoppingcart) by @Crisane and re-add him to the authors.

Kind Regards

**Comment by bomshteyn** [comment]
Hi @bumbummen99 this is not a fork of the repo by Crisane, this package was written from scratch by @avrahamappel sponsored by Bomshteyn Consulting.

**Comment by bomshteyn** [comment]
I have added it as inspired by :-)

**Comment by bumbummen99** [comment]
Oops, **sorry** it looks like i have clicked on the wrong reply/repo -.- I really should not work that late, everything is good here :+1:
