### ISSUE TITLE
Hi there i keep getting this error no matter what i do

### ISSUE THREAD

**Issue by zcwessels** [treeStoneIT/shopping-cart#5]
"Argument 1 passed to Treestoneit\ShoppingCart\CartManager::add() must implement interface Treestoneit\ShoppingCart\Buyable, null given, called in /home/vagrant/Code/ecoms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 245 ◀"

![image](https://user-images.githubusercontent.com/31216542/70157733-c43ab300-16be-11ea-980d-74c5f66f50b0.png)

![image](https://user-images.githubusercontent.com/31216542/70157756-ce5cb180-16be-11ea-9f8e-da660706f081.png)

![image](https://user-images.githubusercontent.com/31216542/70157793-dd436400-16be-11ea-8a25-45c94bc99a9a.png)

![image](https://user-images.githubusercontent.com/31216542/70157859-f9df9c00-16be-11ea-9324-3c8de9075106.png)

**Comment by tominon** [comment]
The first argument of the function `add` needs to be `Product` itself:

```php
$product = Product::findOrFail($request->pid);
Cart::add($product,  1);
```
